clients/urls.py
from django.urls import path, re_path, include

from .views import *

urlpatterns = [
    path("", index, name="home"),
    path("/admin", redirect_to_external_site, name="site-admin"),
    path("filterbytag/<str:slug>/", FilterByTag.as_view(), name="filterbytag"),
    # path("export/", clients_export_to_excel,{'model':'client','orderby': 'pk', 'filterby':''}, name="export_to_excel"),
    # path("export/<str:model>/", clients_export_to_excel, {'orderby': 'pk', 'filterby':''} , name="export_to_excel"),
    # path("export/<str:model>/<str:orderby>/", clients_export_to_excel,{'filterby':''}, name="export_to_excel"),
    # path("export/<str:model>/<str:orderby>/<str:filterby>/", clients_export_to_excel, name="export_to_excel"),
    # re_path(r'^export/(?P<model>\d+)?$', clients_export_to_excel, name='export_to_excel'),
    path(
        "export/",
        include(
            [
                path("", clients_export_to_excel,{'model':'client','orderby': 'pk', 'filterrows':''}, name="export_to_excel"),
                path("<str:model>/", clients_export_to_excel, {'orderby': 'pk', 'filterrows':''} , name="export_to_excel"),
                path("<str:model>/<str:orderby>/", clients_export_to_excel,{'filterrows':''}, name="export_to_excel"),
                path("<str:model>/<str:orderby>/<str:filterrows>/", clients_export_to_excel, name="export_to_excel"),
            ]
        ),
    ),

    # path("logs/<str:app>/<str:mdl>/<int:id>", IslogListView.as_view(), name="log_list"),
    # # path("search/", Search.as_view(), name="search"),
    # path(
    #     "adminka/",
    #     include(
    #         [
    #             # path("", TagListView.as_view(), name="tag_list"),
    #             path("logs/", AdminkaIslogListView.as_view(), name="adminka_log_list"),
    #             # path("create/", TagCreateView.as_view(), name="tag_create"),
    #             # path("<str:slug>/", TagDetailView.as_view(), name="tag_detail"),
    #             # path("<str:slug>/update/", TagUpdateView.as_view(), name="tag_update"),
    #             path("logs/<int:pk>/delete/", IslogDeleteView.as_view(), name="islog_delete"),
    #         ]
    #     ),
    # ),
    path(
        "tags/",
        include(
            [
                path("", TagListView.as_view(), name="tag_list"),
                path("create/", TagCreateView.as_view(), name="tag_create"),
                path("<str:slug>/", TagDetailView.as_view(), name="tag_detail"),
                path("<str:slug>/update/", TagUpdateView.as_view(), name="tag_update"),
                path("<str:slug>/delete/", TagDeleteView.as_view(), name="tag_delete"),
            ]
        ),
    ),
    path(
        "access/",
        include(
            [
                path("", AccessListView.as_view(), name="access_list"),
                path("create/", AccessCreateView.as_view(), name="access_create"),
                path("<str:slug>/", AccessDetailView.as_view(), name="access_detail"),
                path("<str:slug>/update/", AccessUpdateView.as_view(), name="access_update"),
                path("<str:slug>/delete/", AccessDeleteView.as_view(), name="access_delete"),
                path("filter/<str:slug>/", AccessListView.as_view(), name="access_list_by_client"),
            ]
        ),
    ),
    path(
        "contacts/",
        include(
            [
                path("", ContactListView.as_view(), name="contact_list"),
                path("create/", ContactCreateView.as_view(), name="contact_create"),
                path("<str:slug>/", ContactDetailView.as_view(), name="contact_detail"),
                path("<str:slug>/update/", ContactUpdateView.as_view(), name="contact_update"),
                path("<str:slug>/delete/", ContactDeleteView.as_view(), name="contact_delete"),
            ]
        ),
    ),
    path(
        "clients/",
        include(
            [
                path("", ClientListView.as_view(), name="client_list"),
                path("create/", ClientCreateView.as_view(), name="client_create"),
                path("<str:slug>/", ClientDetailView.as_view(), name="client_detail"),
                path("<str:slug>/update/", ClientUpdateView.as_view(), name="client_update"),
                path("<str:slug>/delete/", ClientDeleteView.as_view(), name="client_delete"),
            ]
        ),
    ),
    path(
        "cities/",
        include(
            [
                path("", CityListView.as_view(), name="city_list"),
                path("create/", CityCreateView.as_view(), name="city_create"),
                path("<str:slug>/", CityDetailView.as_view(), name="city_detail"),
                path("<str:slug>/update/", CityUpdateView.as_view(), name="city_update"),
                path("<str:slug>/delete/", CityDeleteView.as_view(), name="city_delete"),
            ]
        ),
    ),
    path(
        "distr/",
        include(
            [
                path("", DistrListView.as_view(), name="distr_list"),
                path("create/", DistrCreateView.as_view(), name="distr_create"),
                path("<int:pk>/", DistrDetailView.as_view(), name="distr_detail"),
                path("<int:pk>/update/", DistrUpdateView.as_view(), name="distr_update"),
                path("<int:pk>/delete/", DistrDeleteView.as_view(), name="distr_delete"),
            ]
        ),
    ),
    path(
        "street/",
        include(
            [
                path("", StreetListView.as_view(), name="street_list"),
                path("create/", StreetCreateView.as_view(), name="street_create"),
                path("<int:pk>/", StreetDetailView.as_view(), name="street_detail"),
                path("<int:pk>/update/", StreetUpdateView.as_view(), name="street_update"),
                path("<int:pk>/delete/", StreetDeleteView.as_view(), name="street_delete"),
            ]
        ),
    ),
    path(
        "fulladdress/",
        include(
            [
                path("", FulladdressListView.as_view(), name="fulladdress_list"),
                path("create/", FulladdressCreateView.as_view(), name="fulladdress_create"),
                path("<int:pk>/", FulladdressDetailView.as_view(), name="fulladdress_detail"),
                path("<int:pk>/update/", FulladdressUpdateView.as_view(), name="fulladdress_update"),
                path("<int:pk>/delete/", FulladdressDeleteView.as_view(), name="fulladdress_delete"),
            ]
        ),
    ),



]

clientsmanag/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

handler404 = 'clients.views.page_not_found_view'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path("", include("clients.urls")),
    path("accounts/", include("accounts.urls")),
    path("finances/", include("finances.urls")),
    path("logs/", include("logs.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

logs/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    # path("logs/<str:app>/<str:mdl>/<int:id>", IslogListView.as_view(), name="log_list"),
    # path("search/", Search.as_view(), name="search"),
    path(
        "",
        include(
            [
                # path("", TagListView.as_view(), name="tag_list"),
                path("", IslogListView.as_view(), name="islog_list"),
                # path("create/", TagCreateView.as_view(), name="tag_create"),
                # path("<str:slug>/", TagDetailView.as_view(), name="tag_detail"),
                # path("<str:slug>/update/", TagUpdateView.as_view(), name="tag_update"),
                path("<int:pk>/delete/", IslogDeleteView.as_view(), name="islog_delete"),
                path("<str:app>/<str:mdl>/<int:id>", FilterIslogListView.as_view(), name="filter_islog_list"),
            ]
        ),
    ),
]

logs/models.py
from django.db import models
# from phone_field import PhoneField
# from django.core.validators import RegexValidator
from django.urls import reverse
# from django.utils.text import slugify
# from transliterate import translit
from django.contrib.auth import get_user_model

    

from libs.logs_adddata import action_tag


class Islog(models.Model):
    # id, app_label, obj_model, obj_id, mess, action_tag, user_id, date_time
    app_label = models.CharField(max_length=100, default='clients', verbose_name="app_label")
    obj_model = models.CharField(max_length=100, verbose_name="obj_model")
    obj_id = models.IntegerField(default=0, verbose_name="obj_id")
    mess = models.TextField(blank=True)
    action_tag = models.IntegerField(default=0, verbose_name="action_tag", choices=action_tag)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.mess

    # def get_absolute_url(self):
    #     return reverse("access_detail", kwargs={"slug": self.slug})

    # def get_absolute_url_for_update(self):
    #     return reverse("access_update", kwargs={"slug": self.slug})

    def get_absolute_url_for_delete(self):
        return reverse("islog_delete", kwargs={"pk": self.pk})

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(translit(self.name, "uk", reversed=True))
    #     super(Access, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Log"
        verbose_name_plural = "Logs"
        ordering = ["date_time"]

clients/templates/clients/access_list.html
{% extends 'base.html' %}
{% load static %}
{% load breadcrumbs %}
{% load search %}

{% block title %}{{ title }} :: {{ block.super }}{% endblock %}

{% block content %}
<!-- About Section -->
<section id="about" class="about section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
        <h2>{{ title }}</h2>
    </div>
    <!-- End Section Title -->

    <div class="container">

        <div class="row">
            <div class="col-lg-4">
                <a href="{{ new_url }}" class="btn btn-success">
                    <i class="bi bi-plus-lg"></i> {{elems.add}}</a>
            </div>
            <div class="col-lg-6">
                {% search_field %}
            </div>
            <div class="col-lg-2">
                <a href="{% url 'export_to_excel' model=mdl orderby=sort filterrows=filter  %}" class="btn btn-secondary"><i class="bi bi-file-earmark-arrow-down"> </i>  {{elems.exp}}</a>
            </div>
        </div>
        <br>

        <div class="row">
            {% if items.exists %}
            <div class="table">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            {% for key,value in columnames.items %}
                            {% if key in show_colums %}
                                <th scope="col">{{value}}  
                                {% if key in sort_fields %}
                                    <!-- <div class="btn-group-vertical btn-group-sm"> -->
                                    <div class="btn-group btn-group-sm">
                                        <a href="{{ this_url }}?sort={{key}}" ><i class="bi bi-caret-up-square"></i></a>
                                        <a href="{{ this_url }}?sort=-{{key}}" ><i class="bi bi-caret-down-square"></i></a>
                                    </div>
                                {% endif %}
                                </th>
                            {% endif %}
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in items %}
                        <tr>
                            <th scope="row">{{item.pk}}</th>
                            <td><a href="{{ item.get_absolute_url }}" style="color: black;  font-weight: bold;">{{item.name}}</a></td>
                            <td><a href="{{ item.client.get_absolute_url }}" style="color: black;">{{item.client}}</a></td>
                            <td>{{item.app}}</td>
                            <td>{{item.idinapp}}</td>
                            <td>{{item.passinapp}}</td>
                            <td>{{item.order}}</td>
                            <!-- <td>{{item.comment}}</td> -->
                            <td>
                                <div class="btn-group">
                                    <a href="{% url dtl_url item.slug %}" 
                                        class="btn btn-outline-secondary btn-sm"
                                        data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-placement="bottom" data-bs-content="{{elems.show}}"
                                        ><i class="bi bi-eye-fill"></i></a>
                                    <a href="{% url upd_url item.slug %}"
                                        class="btn btn-outline-secondary btn-sm" 
                                        data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-placement="bottom" data-bs-content="{{elems.edit}}"
                                        ><i class="bi bi-pencil-fill"></i>
                                    </a>
                                    <a href="{% url del_url item.slug %}"
                                        class="btn btn-outline-secondary btn-sm" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-placement="bottom" data-bs-content="{{elems.del}}"
                                        ><i class="bi bi-x-square-fill"></i></a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
        </div>
        {% include 'inc/_pagination.html' %}
    </div>
</section><!-- /About Section -->
{% endblock %}

clients/templates/clients/city_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }} :: {{ block.super }}{% endblock %}

{% block content %}


<!-- About Section -->
<section id="about" class="about section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
        <h2>{{ title }}</h2>
    </div>
    <!-- End Section Title -->

    <!-- topbar -->
    <div class="container">

        <div class="row">
            <!-- <div class="col-lg-4 sidebar">
                    {{item.name}}
                </div>
                <div class="col-lg-8">
                    {{item.name}}
                </div> -->

            <!-- <div class="card" style="width: 18rem;"> -->
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <div class="card">
                    <!-- <div class="card text-bg-light"> -->
                    <!-- <div class="card text-center"> -->
                    <!-- <div class="card-header">
                            Featured
                        </div> -->
                    <!-- <img src="..." class="card-img-top" alt="..."> -->
                    <div class="card-body">
                        <div class="row g-0">
                            <div class="col-md-2">
                                <span class="card-title">{{card_titles.id}}: </span>
                            </div>
                            <div class="col-md-10">
                                <p><span class="card-text">{{item.id}}</span></p>
                            </div>
                        </div>
                    
                        <div class="row g-0">
                            <div class="col-md-2">
                                <span class="card-title">{{card_titles.name}}: </span>
                            </div>
                            <div class="col-md-10">
                                <p><span class="card-text"><b>
                                    {% if item.settltype %} 
                                    {% for key, value in settltypes.items %}
                                    {% if key == item.settltype and key != 0 %}
                                    {{value}}
                                    {% endif %}
                                    {% endfor %}
                                    {% endif %} 
                                    {% if item.name %} 
                                    {{ item.name }}
                                    {% else %} -- {% endif %}
                                </b></span></p>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer text-body-secondary  text-end">
                        <small class="text-body-secondary"> {{elems.lastupd}} {{lastupd|date:"d.m.Y H:i" }} {{elems.lastupdby}} {{lastupdby}}</small>
                    </div>

                    <div class="card-footer">
                        <div class="row g-0">
                            <div class="col-md-6">
                                <a href="{{ back_url }}" class="btn btn-secondary"><i class="bi bi-arrow-left"></i> {{elems.back}}</a>
                                <a href="{{ item.get_absolute_url_for_logs }}" class="btn btn-outline-secondary"><i class="bi bi-clock-history"></i> {{elems.logs}}</a>
                            </div>
                            <div class="col-md-2 text-center">

                            </div>
                            <div class="col-md-4 text-end">
                                <a href="{{ item.get_absolute_url_for_update }}" class="btn btn-primary"><i
                                        class="bi bi-pencil-fill"></i> {{elems.edit}}</a>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
            <div class="col-lg-3">

            </div>




        </div>



    </div>

</section><!-- /About Section -->




{% endblock %}

clients/templates/clients/city_list.html
{% extends 'base.html' %}
{% load static %}
{% load breadcrumbs %}
{% load search %}
{% load is_modal %}

{% block title %}{{ title }} :: {{ block.super }}{% endblock %}

{% block content %}
<!-- About Section -->
<section id="about" class="about section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
        <h2>{{ title }}</h2>
    </div>
    <!-- End Section Title -->

    <!-- topbar -->
    <div class="container">

        <div class="row">
            <div class="col-lg-4">
                <a href="{{ new_url }}" class="btn btn-success"><i class="bi bi-plus-lg"></i> {{elems.add}}</a>
            </div>
            <div class="col-lg-6">
                {% search_field %}
            </div>
            <div class="col-lg-2">
                {% comment %} {% add_city %} {% endcomment %}
                <a href="{% url 'export_to_excel' model=mdl orderby=sort filterrows=filter  %}" class="btn btn-secondary"><i class="bi bi-file-earmark-arrow-down"> </i>  {{elems.exp}}</a>
            </div>
            <br>

            <div class="row">
                {% if items.exists %}
                <div class="table">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                {% for key,value in columnames.items %}
                                {% if key in show_colums %}
                                    <th scope="col">{{value}}  
                                    {% if key in sort_fields %}
                                        <!-- <div class="btn-group-vertical btn-group-sm"> -->
                                        <div class="btn-group btn-group-sm">
                                            <a href="{{ this_url }}?sort={{key}}" ><i class="bi bi-caret-up-square"></i></a>
                                            <a href="{{ this_url }}?sort=-{{key}}" ><i class="bi bi-caret-down-square"></i></a>
                                        </div>
                                    {% endif %}
                                    </th>
                                {% endif %}
                                {% endfor %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in items %}
                            <tr>
                                <th scope="row">{{item.pk}}</th>
                                <td>
                                    <a href="{{ item.get_absolute_url }}" style="color: black;  font-weight: bold;" >
                                        {% if item.settltype %} 
                                        {% for key, value in settltypes.items %}
                                        {% if key == item.settltype and key != 0 %}
                                        {{value}}
                                        {% endif %}
                                        {% endfor %}
                                        {% endif %} 
                                        {% if item.name %} 
                                        {{ item.name }}
                                        {% else %} -- {% endif %}
                                    </a>
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{% url dtl_url item.slug %}" 
                                            class="btn btn-outline-secondary btn-sm"
                                            data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-placement="bottom" data-bs-content="{{elems.show}}"
                                            ><i class="bi bi-eye-fill"></i></a>
                                        <a href="{% url upd_url item.slug %}"
                                            class="btn btn-outline-secondary btn-sm" 
                                            data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-placement="bottom" data-bs-content="{{elems.edit}}"
                                            ><i class="bi bi-pencil-fill"></i>
                                        </a>
                                        <a href="{% url del_url item.slug %}"
                                            class="btn btn-outline-secondary btn-sm" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-placement="bottom" data-bs-content="{{elems.del}}"
                                            ><i class="bi bi-x-square-fill"></i></a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            </div>
            {% include 'inc/_pagination.html' %}
        </div>
</section><!-- /About Section -->
{% endblock %}

clients/templates/clients/contact_list.html
{% extends 'base.html' %}
{% load static %}
{% load breadcrumbs %}
{% load search %}

{% block title %}{{ title }} :: {{ block.super }}{% endblock %}

{% block content %}
<!-- About Section -->
<section id="about" class="about section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
        <h2>{{ title }}</h2>
    </div>
    <!-- End Section Title -->

    <!-- topbar -->
    <div class="container">

        <div class="row">
            <div class="col-lg-4">
                <a href="{{ new_url }}" class="btn btn-success">
                    <i class="bi bi-plus-lg"></i> {{elems.add}}</a>
            </div>
            <div class="col-lg-6">
                {% search_field %}
            </div>
            <div class="col-lg-2">
                <a href="{% url 'export_to_excel' model=mdl orderby=sort filterrows=filter  %}" class="btn btn-secondary"><i class="bi bi-file-earmark-arrow-down"> </i>  {{elems.exp}}</a>
            </div>
            <br>

            <div class="row">
                {% if items.exists %}
                <div class="table">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                {% for key,value in columnames.items %}
                                {% if key in show_colums %}
                                    <th scope="col">{{value}}  
                                    {% if key in sort_fields %}
                                        <!-- <div class="btn-group-vertical btn-group-sm"> -->
                                        <div class="btn-group btn-group-sm">
                                            <a href="{{ this_url }}?sort={{key}}" ><i class="bi bi-caret-up-square"></i></a>
                                            <a href="{{ this_url }}?sort=-{{key}}" ><i class="bi bi-caret-down-square"></i></a>
                                        </div>
                                    {% endif %}
                                    </th>
                                {% endif %}
                                {% endfor %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in items %}
                            <tr>
                                <th scope="row">{{item.pk}}</th>
                                <td><a href="{{ item.get_absolute_url }}" style="color: black;  font-weight: bold;" >{{item.name}}</a></td>
                                <td>
                                    {% if item.phone1 is not None %}{{item.phone1}}{% endif %}
                                    {% if item.phone2 is not None %}, {{item.phone2}}{% endif %}
                                    {% if item.phone3 is not None %}, {{item.phone3}}{% endif %}
                                </td>
                                <td>{{item.email}}</td>
                                <!-- {% for key, value in client_type.items %}
                                    {% if key == item.type %}
                                    <td>{{value}}</td>
                                    {% endif %}
                                    {% endfor %} -->
                                <td><a href="{{ item.client.get_absolute_url }}" style="color: black;">{{item.client}}</a></td>
                                <td>{{item.position}}</td>
                                <td>{{item.order}}</td>
                                <!-- <td>{{item.comment}}</td> -->
                                <td>
                                    <div class="btn-group">
                                        <a href="{% url dtl_url item.slug %}" 
                                            class="btn btn-outline-secondary btn-sm"
                                            data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-placement="bottom" data-bs-content="{{elems.show}}"
                                            ><i class="bi bi-eye-fill"></i></a>
                                        <a href="{% url upd_url item.slug %}"
                                            class="btn btn-outline-secondary btn-sm" 
                                            data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-placement="bottom" data-bs-content="{{elems.edit}}"
                                            ><i class="bi bi-pencil-fill"></i>
                                        </a>
                                        <a href="{% url del_url item.slug %}"
                                            class="btn btn-outline-secondary btn-sm" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-placement="bottom" data-bs-content="{{elems.del}}"
                                            ><i class="bi bi-x-square-fill"></i></a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            </div>
            {% include 'inc/_pagination.html' %}
        </div>
</section><!-- /About Section -->
{% endblock %}

clients/templates/clients/menu_tpl.html
<nav id="navmenu" class="{{ menu_class }}">
    <ul>
        {% for item in items %}
        {% if item.childs == 0 %}
        <li><a href="{{ item.url }}">{{ item.title }}</a></li>
        <!-- <li><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></li> -->
        {% else %}
        <li class="dropdown"><a href="{{ item.url }}"><span>{{ item.title }}</span> <i
                    class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
                {% for child in item.childs %}
                <li><a href="{{ child.url }}">{{ child.title }}</a></li>
                {% endfor %}
            </ul>
        </li>
        {% endif %}
        {% endfor %}

        {% if perms.clients.view_islog %}
            <li>dfsdkfnkds</li>ntcn
        {% endif %}

            <!-- <li><a href="blog.html">Blog</a></li>
        <li class="dropdown"><a href="#"><span>Dropdown</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
                <li><a href="#">Dropdown 1</a></li>
                <li class="dropdown"><a href="#"><span>Deep Dropdown</span> <i
                            class="bi bi-chevron-down toggle-dropdown"></i></a>
                    <ul>
                        <li><a href="#">Deep Dropdown 1</a></li>
                        <li><a href="#">Deep Dropdown 2</a></li>
                        <li><a href="#">Deep Dropdown 3</a></li>
                        <li><a href="#">Deep Dropdown 4</a></li>
                        <li><a href="#">Deep Dropdown 5</a></li>
                    </ul>
                </li>
                <li><a href="#">Dropdown 2</a></li>
                <li><a href="#">Dropdown 3</a></li>
                <li><a href="#">Dropdown 4</a></li>
            </ul>
        </li>
        <li><a href="#contact">Contact</a></li> -->



    </ul>
    <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
</nav>