clientsmanag/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

handler404 = 'clients.views.page_not_found_view'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path("", include("clients.urls")),
    path("accounts/", include("accounts.urls")),
    path("finances/", include("finances.urls")),
    path("logs/", include("logs.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

logs/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    # path("logs/<str:app>/<str:mdl>/<int:id>", IslogListView.as_view(), name="log_list"),
    # path("search/", Search.as_view(), name="search"),
    path(
        "",
        include(
            [
                # path("", TagListView.as_view(), name="tag_list"),
                path("", IslogListView.as_view(), name="islog_list"),
                # path("create/", TagCreateView.as_view(), name="tag_create"),
                # path("<str:slug>/", TagDetailView.as_view(), name="tag_detail"),
                # path("<str:slug>/update/", TagUpdateView.as_view(), name="tag_update"),
                path("<int:pk>/delete/", IslogDeleteView.as_view(), name="islog_delete"),
                path("<str:app>/<str:mdl>/<int:id>", FilterIslogListView.as_view(), name="filter_islog_list"),
            ]
        ),
    ),
]

logs/models.py
from django.db import models
# from phone_field import PhoneField
# from django.core.validators import RegexValidator
from django.urls import reverse
# from django.utils.text import slugify
# from transliterate import translit
from django.contrib.auth import get_user_model

    

from libs.logs_adddata import action_tag


class Islog(models.Model):
    # id, app_label, obj_model, obj_id, mess, action_tag, user_id, date_time
    app_label = models.CharField(max_length=100, default='clients', verbose_name="app_label")
    obj_model = models.CharField(max_length=100, verbose_name="obj_model")
    obj_id = models.IntegerField(default=0, verbose_name="obj_id")
    mess = models.TextField(blank=True)
    action_tag = models.IntegerField(default=0, verbose_name="action_tag", choices=action_tag)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.mess

    # def get_absolute_url(self):
    #     return reverse("access_detail", kwargs={"slug": self.slug})

    # def get_absolute_url_for_update(self):
    #     return reverse("access_update", kwargs={"slug": self.slug})

    def get_absolute_url_for_delete(self):
        return reverse("islog_delete", kwargs={"pk": self.pk})

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(translit(self.name, "uk", reversed=True))
    #     super(Access, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Log"
        verbose_name_plural = "Logs"
        ordering = ["date_time"]

templates/inc/_footer.html
<footer id="footer" class="footer dark-background">

    <!-- <div class="footer-newsletter">
        <div class="container">
            <div class="row justify-content-center text-center">
                <div class="col-lg-6">
                    <h4>Join Our Newsletter</h4>
                    <p>Subscribe to our newsletter and receive the latest news about our products and services!</p>
                    <form action="forms/newsletter.php" method="post" class="php-email-form">
                        <div class="newsletter-form"><input type="email" name="email"><input type="submit"
                                value="Subscribe"></div>
                        <div class="loading">Loading</div>
                        <div class="error-message"></div>
                        <div class="sent-message">Your subscription request has been sent. Thank you!</div>
                    </form>
                </div>
            </div>
        </div>
    </div> -->

    <div class="container footer-top">
        <div class="row gy-4">
            <div class="col-lg-4 col-md-6 footer-about">
                <a href="index.html" class="d-flex align-items-center">
                    <span class="sitename">Arsha</span>
                </a>
                <div class="footer-contact pt-3">
                    <p>A108 Adam Street</p>
                    <p>New York, NY 535022</p>
                    <p class="mt-3"><strong>Phone:</strong> <span>+1 5589 55488 55</span></p>
                    <p><strong>Email:</strong> <span>info@example.com</span></p>
                </div>
            </div>

            <div class="col-lg-2 col-md-3 footer-links">
                <h4>Useful Links</h4>
                <ul>
                    <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
                    <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
                    <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
                    <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
                </ul>
            </div>

            <div class="col-lg-2 col-md-3 footer-links">
                <h4>Our Services</h4>
                <ul>
                    <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
                    <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
                    <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
                    <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
                </ul>
            </div>

            <div class="col-lg-4 col-md-12">
                <h4>Follow Us</h4>
                <p>Cras fermentum odio eu feugiat lide par naso tierra videa magna derita valies</p>
                <div class="social-links d-flex">
                    <a href=""><i class="bi bi-twitter-x"></i></a>
                    <a href=""><i class="bi bi-facebook"></i></a>
                    <a href=""><i class="bi bi-instagram"></i></a>
                    <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
            </div>

        </div>
    </div>

    <div class="container copyright text-center mt-4">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">Arsha</strong> <span>All Rights Reserved</span>
        </p>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you've purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> Distributed by <a
                href="https://themewagon.com" target="_blank">ThemeWagon</a>
        </div>
    </div>

</footer>

templates/inc/_header.html
{% load menu %}
<header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center">

        {% show_logo %}

        {% if perms.clients.delete_islog %}
        {% show_menu 'foradmins' %}
        {% else %}
        {% show_menu %}
        {% endif %}

        <!-- <a class="btn-getstarted" href="#about">Get Started</a> -->

        {% if request.user.is_authenticated %}
        <!-- <span class="btn-getstarted">{{ user.username }} | <a class="" style="color: white;" href="{% url 'logout' %}">Вихід</a></span> -->
        <!-- <span class="btn-getstarted">{{ user.username }} | <a class="" style="color: white;" href="{% url 'logout' %}">Вихід</a></span> -->
        <span class="btn-getstarted"><a href="{% url 'user_detail' %}" style="color: white;">{% if user.first_name %}{{user.first_name}}{% else %}{{user.username}}{% endif %}</a>  | <a class="" style="color: white;" href="{% url 'logout' %}">Вихід</a></span>
        {% else %}
        <a class="btn-getstarted" href="{% url 'login' %}">Вхід</a>
        {% endif %}




    </div>
</header>

templates/inc/_pagination.html
{% if page_obj.paginator.count %}
    <p>
        Показано {{ page_obj.start_index }}-{{ page_obj.end_index }} з {{ page_obj.paginator.count }} записів.
    </p>
{% else %}
    <div class="alert alert-danger" role="alert">
        {{err_msg}}
    </div>
{% endif %}
{% if page_obj.has_other_pages %}
<div class="row">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{{ s }}page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
            {% for p in page_obj.paginator.page_range %}
            {% if page_obj.number == p %}
            <li class="page-item active"><a class="page-link" href="?{{ s }}page={{p}}">{{ p }}</a></li>
            {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %} <!-- <li class="page-item"><a
                    class="page-link" href="?page={{p}}">{{ p }}</a></li> -->
                <li class="page-item"><a class="page-link" href="?{{ s }}page={{ p }}">{{ p }}</a></li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{{ s }}page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
        </ul>
    </nav>
</div>
{% endif %}